version: '3.7'

services:
  portfolio-react-prod-eugenia:
    environment:
      VIRTUAL_HOST: euge.dev
      LETSENCRYPT_HOST: euge.dev
      LETSENCRYPT_EMAIL: eugeniasalazar745@gmail.com
      VIRTUAL_PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    container_name: portfolio-eugenia-nodejs-server
    volumes:
      - .:/usr/src/app/portfolio
      - ./build:/usr/src/app/portfolio/build
      - /usr/src/app/portfolio/node_modules

networks:
  default:
    external:
      name: nginx-proxy
